# This is a basic workflow to help you get started with Actions

name: Cypress GitHub Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          'node:version': '14'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        run: | 
             npm install cypress  
             node_modules/.bin/cypress run --reporter mochawesome
      - name: Storing report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mochawesome-report
          path: ./mochawesome-report
          retention-days: 2
            
