# This is a basic workflow to help you get started with Actions

name: Cypress GitHub Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   cypress-test:
     name: Chrome Run
     runs-on: ubuntu-18.04
     container: cypress/browser:node12.18.0-chrome83-ff7
     steps:
       - uses: actions/checkout@v2
       
       - name: Install Cypress
         run: |
           npm ci
           $(npm bin)/cypress verify
           
       - name: Run Cypress Tests
         run: npm test:chrome
         continue-on-error: false
